In [2]:
import pandas as pd

# Read the CSV file
df = pd.read_csv('PonziDataset_20221114.csv')

# Print the first 5 rows
filtered_df = df[['address', 'label']]
filtered_df[:5]
filtered_df.shape

(6498, 2)

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Read the CSV file
df = pd.read_csv('PonziDataset_20221114.csv')

# Extract features (X) and labels (Y)
X = df['address']  # Assuming 'label' is the column you want to predict
Y = df['label']

# Assuming you have normalized your data and assigned it to normalized_data_array
# If not, you may need to perform normalization on your features before splitting the data

# Perform train-test split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1, random_state=42, stratify=Y)

# Now, you can save the train and test datasets to separate CSV files
train_data = pd.concat([X_train, Y_train], axis=1)
test_data = pd.concat([X_test, Y_test], axis=1)

# Save to CSV files
train_data.to_csv('train_data.csv', index=False)
test_data.to_csv('test_data.csv', index=False)

In [5]:
import pandas as pd

# Load train and test datasets
train_data = pd.read_csv('train_data.csv')
test_data = pd.read_csv('test_data.csv')

# Check the shapes
print("Train data shape:", train_data.shape)
print("Test data shape:", test_data.shape)

test_data.head()

Train data shape: (5848, 2)
Test data shape: (650, 2)

                                      address  label
0  0x31919e139a2688da420ef73195b7751951058384      0
1  0x8eca2366e8ad2051a14af338620f6dd101c231e1      0
2  0x2dcfaac11c9eebd8c6c42103fe9e2a6ad237af27      0
3  0x36efee477f68c136139abeb219be6c2254711d0a      0
4  0x5935b9cfebf9807925b2e2b727aca214a0c18fc8      0

In [10]:

# Read the CSV file
df = pd.read_csv('PonziDataset_20221114.csv')

# df=df[:6498]

# Filter rows where label is equal to 1 and select 'address' and 'label' columns
# filtered_df = df[df['label'] == 1][['address', 'label']]

filtered_df = df[df['label'] == 0][['address', 'label']]

# Print the first 10 rows of filtered DataFrame
filtered_df.shape

(6184, 2)

In [3]:
from etherscan import *

# Read the CSV file
# df = pd.read_csv('PonziDataset_20221114.csv')

# get a list of contract adresses using df 
contract_adresses = df['address'].tolist()
# get first 5 contract adresses
contract_adresses = contract_adresses[:5]


eth_api = ETH_API("74EXH3ZYYXPYAA9M1AAUCHSXXQ62MVXANW",contract_adresses)
# transactions = eth_api.get_last_x_transactions("0xe82719202e5965cf5d9b6673b7503a3b92de20be", 1)
# print(transactions)
eth_api.createTransactionFiles()
eth_api.createInternalTransactionFiles()

=== Downloading transaction files...
772
1 transactions have downloaded...
211
2 transactions have downloaded...
2021
3 transactions have downloaded...
461
4 transactions have downloaded...
558
5 transactions have downloaded...
ponzi transactions downloading is over.
=== Downloading internal transaction files...
Error: No transactions found
1 transactions have downloaded...
3803
2 transactions have downloaded...
2002
3 transactions have downloaded...
494
4 transactions have downloaded...
349
5 transactions have downloaded...
ponzi transactions downloading is over.

True

In [5]:
from feature_extraction import *

# Read the CSV file
# df = pd.read_csv('PonziDataset_20221114.csv')

# get a list of contract adresses using df 
contract_adresses = df['address'].tolist()
# get first 5 contract adresses
contract_adresses = contract_adresses[:5]


fe = ContractFeature(contract_adresses[0],True)
fe.get_balance()

['blockNumber', 'blockHash', 'timeStamp', 'hash', 'nonce', 'transactionIndex', 'from', 'to', 'value', 'gas', 'gasPrice', 'input', 'contractAddress', 'cumulativeGasUsed', 'gasUsed', 'confirmations', 'isError']
['16437430', '0x86d746a835a01c095cc4cf57f041054d10e66eae260ca27d5244e281738bfa26', '1674090023', '0x567582f8b61c54f62a80d2ec84d9715d4539b8a20d60a66abdd157e23f6bf293', '1895', '44', '0x76da9f88e63a85ba8bfa19f3821d5a271753d3dc', '0x6e38a457c722c6011b2dfa06d49240e797844d66', '0', '35001', '39121343504', '0x6bd5084a', '', '2181692', '23334', '2273370', '0']
['16437450', '0x16be779052c4bc38241938117d0b3bed7ff84c46f53eccec8577f3f94594ae13', '1674090263', '0x17d80f1e5b0ad0af9ffc620681e2c6c5560e803fb99a492ca705ee7522f315f2', '1896', '96', '0x76da9f88e63a85ba8bfa19f3821d5a271753d3dc', '0x6e38a457c722c6011b2dfa06d49240e797844d66', '0', '174915', '33525824781', '0xf3fe12c9000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000146c6f72646769762e657468207761732068657265000000000000000000000000', '', '9803694', '116610', '2273350', '0']
['16447154', '0xc6534c1aa14181ff79ec6762e768663350bffe0e78ce8bcf102c5a66a6040a58', '1674207311', '0xaad8e18a78e1c82f470f3e6b6f98c466ce0a425839315e71057e9514aec67dba', '757', '186', '0x1ea565809cc3883548f2e5f7a429e0cc88fdd6fb', '0x6e38a457c722c6011b2dfa06d49240e797844d66', '0', '174861', '14552060281', '0xf3fe12c90000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001148692050617261676f6e6963616c69736d000000000000000000000000000000', '', '19751769', '116574', '2263646', '0']
['17856260', '0xfdc542b5228d78c8b5bc13ad80f6ad5bbb2115f4266f0715edc57f973b16ca9a', '1691329043', '0xcf203a9dd5811e2fecd7d482d43ebc1bf96649c2b1f1890b7ff57adea7b41a49', '2170', '119', '0x303052148a78a692d7aa89bad454f3e91785488d', '0x6e38a457c722c6011b2dfa06d49240e797844d66', '0', '174825', '19206712947', '0xf3fe12c90000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000f5069786c732077617320686572652e0000000000000000000000000000000000', '', '12666735', '116550', '854540', '0']
['17857156', '0x09e1436e85139b36ca364eaa7de572325b0aebcc6605fa1c794bc11b8c370793', '1691339903', '0xaa4381e88ed867f32476533857c43bb84f1645a0d0d574980bf5bd083a4f79bf', '232', '71', '0xaa5124f1128962ae115588611a6467ce318c8081', '0x6e38a457c722c6011b2dfa06d49240e797844d66', '0', '174807', '25206357445', '0xf3fe12c90000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000e706f6e6b69207761732068657265000000000000000000000000000000000000', '', '7730495', '116538', '853644', '0']
['17857156', '0x09e1436e85139b36ca364eaa7de572325b0aebcc6605fa1c794bc11b8c370793', '1691339903', '0x97f033a06ac694cc9680338639bb4216040fbac01912add807a34e6b69961f78', '233', '86', '0xaa5124f1128962ae115588611a6467ce318c8081', '0x6e38a457c722c6011b2dfa06d49240e797844d66', '0', '174825', '25206357445', '0xf3fe12c90000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000f506f6e6b692077617320686572652e0000000000000000000000000000000000', '', '9511135', '116550', '853644', '0']
['18345794', '0x5c3808accb1ffbe00ea7ae9feca71c9cac2e60fb2a857a8fbe5259fe2a1d89ca', '1697252291', '0x24644157aea094d9b4ad0f311a0b06571dc116f0a5f4e295ec0a1c07f3c83ad8', '1608', '82', '0x686158b2df5cf38d948326fc7f8faac6f3bfd7df', '0x6e38a457c722c6011b2dfa06d49240e797844d66', '0', '174681', '5744365296', '0xf3fe12c90000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000745444f5541524400000000000000000000000000000000000000000000000000', '', '7013765', '116454', '365006', '0']
['18345812', '0x3e27b64111b8e5e1214deea887ad622245c5132d2540d78b34579736764024ab', '1697252507', '0x640435773e2378616eeb8687e8ea6f1d42d06395b470dcb80554cc60597de82c', '1609', '84', '0x686158b2df5cf38d948326fc7f8faac6f3bfd7df', '0x6e38a457c722c6011b2dfa06d49240e797844d66', '0', '35001', '5897406433', '0x6bd5084a', '', '7216100', '23334', '364988', '0']
['18345871', '0x8dd9624de688d8f6388d0e3c4d5ab5b473595a11669a75cf0af50495784d8e53', '1697253227', '0x4376cc02774a92d3f5f78905d81e26dbd57f9504fd05acd4628f492525b294e9', '370', '80', '0x698f3eaf3defee3c5a00b64bd65feee9015d6970', '0x6e38a457c722c6011b2dfa06d49240e797844d66', '0', '174681', '7354807204', '0xf3fe12c90000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000765646f7561726400000000000000000000000000000000000000000000000000', '', '5230864', '116454', '364929', '0']
['18640279', '0x9a5c61f1131beb8a620566c246c455839fdeeec5a47c1cc5eea09bf850fa75e6', '1700813363', '0x0ebed233647ff61e0ab635c4dea6f43fb29f0fd29c28975293eccc3af542136a', '152', '86', '0x149c4d3976a8901af1c61f95409e109dccde5e27', '0x6e38a457c722c6011b2dfa06d49240e797844d66', '0', '35001', '33078653108', '0x6bd5084a', '', '9375929', '23334', '70521', '0']
['blockNumber', 'blockHash', 'timeStamp', 'hash', 'nonce', 'transactionIndex', 'from', 'to', 'value', 'gas', 'gasPrice', 'input', 'contractAddress', 'cumulativeGasUsed', 'gasUsed', 'confirmations', 'isError']
['16437430', '0x86d746a835a01c095cc4cf57f041054d10e66eae260ca27d5244e281738bfa26', '1674090023', '0x567582f8b61c54f62a80d2ec84d9715d4539b8a20d60a66abdd157e23f6bf293', '1895', '44', '0x76da9f88e63a85ba8bfa19f3821d5a271753d3dc', '0x6e38a457c722c6011b2dfa06d49240e797844d66', '0', '35001', '39121343504', '0x6bd5084a', '', '2181692', '23334', '2273370', '0']
['16437450', '0x16be779052c4bc38241938117d0b3bed7ff84c46f53eccec8577f3f94594ae13', '1674090263', '0x17d80f1e5b0ad0af9ffc620681e2c6c5560e803fb99a492ca705ee7522f315f2', '1896', '96', '0x76da9f88e63a85ba8bfa19f3821d5a271753d3dc', '0x6e38a457c722c6011b2dfa06d49240e797844d66', '0', '174915', '33525824781', '0xf3fe12c9000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000146c6f72646769762e657468207761732068657265000000000000000000000000', '', '9803694', '116610', '2273350', '0']
['16447154', '0xc6534c1aa14181ff79ec6762e768663350bffe0e78ce8bcf102c5a66a6040a58', '1674207311', '0xaad8e18a78e1c82f470f3e6b6f98c466ce0a425839315e71057e9514aec67dba', '757', '186', '0x1ea565809cc3883548f2e5f7a429e0cc88fdd6fb', '0x6e38a457c722c6011b2dfa06d49240e797844d66', '0', '174861', '14552060281', '0xf3fe12c90000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001148692050617261676f6e6963616c69736d000000000000000000000000000000', '', '19751769', '116574', '2263646', '0']
['17856260', '0xfdc542b5228d78c8b5bc13ad80f6ad5bbb2115f4266f0715edc57f973b16ca9a', '1691329043', '0xcf203a9dd5811e2fecd7d482d43ebc1bf96649c2b1f1890b7ff57adea7b41a49', '2170', '119', '0x303052148a78a692d7aa89bad454f3e91785488d', '0x6e38a457c722c6011b2dfa06d49240e797844d66', '0', '174825', '19206712947', '0xf3fe12c90000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000f5069786c732077617320686572652e0000000000000000000000000000000000', '', '12666735', '116550', '854540', '0']
['17857156', '0x09e1436e85139b36ca364eaa7de572325b0aebcc6605fa1c794bc11b8c370793', '1691339903', '0xaa4381e88ed867f32476533857c43bb84f1645a0d0d574980bf5bd083a4f79bf', '232', '71', '0xaa5124f1128962ae115588611a6467ce318c8081', '0x6e38a457c722c6011b2dfa06d49240e797844d66', '0', '174807', '25206357445', '0xf3fe12c90000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000e706f6e6b69207761732068657265000000000000000000000000000000000000', '', '7730495', '116538', '853644', '0']
['17857156', '0x09e1436e85139b36ca364eaa7de572325b0aebcc6605fa1c794bc11b8c370793', '1691339903', '0x97f033a06ac694cc9680338639bb4216040fbac01912add807a34e6b69961f78', '233', '86', '0xaa5124f1128962ae115588611a6467ce318c8081', '0x6e38a457c722c6011b2dfa06d49240e797844d66', '0', '174825', '25206357445', '0xf3fe12c90000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000f506f6e6b692077617320686572652e0000000000000000000000000000000000', '', '9511135', '116550', '853644', '0']
['18345794', '0x5c3808accb1ffbe00ea7ae9feca71c9cac2e60fb2a857a8fbe5259fe2a1d89ca', '1697252291', '0x24644157aea094d9b4ad0f311a0b06571dc116f0a5f4e295ec0a1c07f3c83ad8', '1608', '82', '0x686158b2df5cf38d948326fc7f8faac6f3bfd7df', '0x6e38a457c722c6011b2dfa06d49240e797844d66', '0', '174681', '5744365296', '0xf3fe12c90000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000745444f5541524400000000000000000000000000000000000000000000000000', '', '7013765', '116454', '365006', '0']
['18345812', '0x3e27b64111b8e5e1214deea887ad622245c5132d2540d78b34579736764024ab', '1697252507', '0x640435773e2378616eeb8687e8ea6f1d42d06395b470dcb80554cc60597de82c', '1609', '84', '0x686158b2df5cf38d948326fc7f8faac6f3bfd7df', '0x6e38a457c722c6011b2dfa06d49240e797844d66', '0', '35001', '5897406433', '0x6bd5084a', '', '7216100', '23334', '364988', '0']
['18345871', '0x8dd9624de688d8f6388d0e3c4d5ab5b473595a11669a75cf0af50495784d8e53', '1697253227', '0x4376cc02774a92d3f5f78905d81e26dbd57f9504fd05acd4628f492525b294e9', '370', '80', '0x698f3eaf3defee3c5a00b64bd65feee9015d6970', '0x6e38a457c722c6011b2dfa06d49240e797844d66', '0', '174681', '7354807204', '0xf3fe12c90000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000765646f7561726400000000000000000000000000000000000000000000000000', '', '5230864', '116454', '364929', '0']
['18640279', '0x9a5c61f1131beb8a620566c246c455839fdeeec5a47c1cc5eea09bf850fa75e6', '1700813363', '0x0ebed233647ff61e0ab635c4dea6f43fb29f0fd29c28975293eccc3af542136a', '152', '86', '0x149c4d3976a8901af1c61f95409e109dccde5e27', '0x6e38a457c722c6011b2dfa06d49240e797844d66', '0', '35001', '33078653108', '0x6bd5084a', '', '9375929', '23334', '70521', '0']

In [5]:
# Read the CSV file
df1 = pd.read_csv('./data/transactions/0x5fe5b7546d1628f7348b023a0393de1fc825a4fd.csv')
df1.head()

,blockNumber,blockHash,timeStamp,hash,nonce,transactionIndex,from,to,value,gas,gasPrice,input,contractAddress,cumulativeGasUsed,gasUsed,confirmations,isError
0,5324162,0x829b1b8ecca1f8d8fd5af6c51393d099d56e20337147...,1522052177,0xe1c30beca1b65e84efd1858e9ecb56915ad9b500edea...,11,78,0x1210c78b189226c1eb0149e1ec4764ebbb19c4ab,0x5fe5b7546d1628f7348b023a0393de1fc825a4fd,100000000000000,34729,5000000000,0xb595b8b5000000000000000000000000000000000000...,NaN,3357710,23153,13190650,0
1,5324169,0xdc77a3723898cfbf458848ba7cddbafca358ced9b794...,1522052298,0xf958218359055472e05ff6f0ddc0473f73c14966a507...,12,46,0x1210c78b189226c1eb0149e1ec4764ebbb19c4ab,0x5fe5b7546d1628f7348b023a0393de1fc825a4fd,100000000000000,34729,5000000000,0xb595b8b5000000000000000000000000000000000000...,NaN,2046652,23153,13190643,0
2,8750859,0xceb4171afd81a15387ade3cebb22442a0ab65a4ef27c...,1571210677,0xca54be37d991264e9f1bf503ea6f2228391c69aef3d7...,14,32,0x5a65d9784371edd534ed11b32ec9446d18383ace,0x5fe5b7546d1628f7348b023a0393de1fc825a4fd,0,34825,1000000000,0xb595b8b5000000000000000000000000000000000000...,NaN,1763156,23217,9763953,0
3,11099463,0xa4da4a6f2ce7caf3fe32583b8a69ff8984433315af67...,1603282525,0x3cb0a01654be508fc407ab3826652adf0b86ced8db3c...,77,123,0x75d7926bd9e475d1d8a0bcaa1c4f0d835d574d9e,0x5fe5b7546d1628f7348b023a0393de1fc825a4fd,0,33228,34000000000,0x41c0e1b5,NaN,12416839,22152,7415349,0
4,12869209,0x0625a1ed11486a6771e4a4f69117b21e921d502d4a27...,1626862647,0x607ada441e85c01650809eb410e560d5c85f8bbe7e30...,13,183,0x36dbeff531486155e8182044b660d76efd11c47e,0x5fe5b7546d1628f7348b023a0393de1fc825a4fd,0,21332,10000000000,0x90fa17bb,NaN,12880982,21332,5645603,0

In [12]:
from etherscan import *


eth_api = ETH_API("74EXH3ZYYXPYAA9M1AAUCHSXXQ62MVXANW")
# Assuming you have the addresses and their transaction counts in a dictionary
transaction_counts = {}

# Assuming you have a loop that populates the transaction_counts dictionary
for address in filtered_df["address"].head(100):
    count= eth_api.get_transactions_count(address)
    print(count)
    transaction_counts[address] = eth_api.get_transactions_count(address)

# Sort the transaction_counts dictionary by values in descending order
sorted_transaction_counts = {k: v for k, v in sorted(transaction_counts.items(), key=lambda item: item[1], reverse=True)}

# Print the sorted transaction counts
print("Sorted Transaction Counts (max to min):", sorted_transaction_counts)

211
474
54
52
420
502
15
527
164
29
4
88
11
3
19
140
15
26
163
41
5
619
5
17
31
24
4
1
19
30
20
13
1
3
24
34
47
13
31
35
8
An error occurred: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))
None
1
18
5
1
2
1
1
6
7
16
13
16
18
15
257
4
3
6
1
4
26
7
36
7
16
13
1
4
1
6
61
7
7
2
2
4
5
17
1
2
8
5
107
3
4
2
3
17
1
82
15
5
1
118
11
1
1
3
Sorted Transaction Counts (max to min): {'0x43bbc7fafb860d974037b8f7dd06b6f6fe799b3e': 619, '0xe82719202e5965cf5d9b6673b7503a3b92de20be': 527, '0xf45717552f12ef7cb65e95476f217ea008167ae3': 502, '0xfd2487cc0e5dce97f08be1bc8ef1dce8d5988b4d': 474, '0xa9e4e3b1da2462752aea980698c335e70e9ab26c': 420, '0xba6284ca128d72b25f1353fadd06aa145d9095af': 257, '0x109c4f2ccc82c4d77bde15f306707320294aea3f': 211, '0xdcb13fa157eebf22ddc8c9aa1d6e394810de6fa3': 164, '0x5e84c1a6e8b7cd42041004de5cd911d537c5c007': 163, '0x1213c29b5e1a6f33e0d044f850a57b665e3cde21': 140, '0xfeeb8a968f0d7fd58e29fbfc525051f50ee2fedc': 118, '0x9758da9b4d001ed2d0df46d25069edf53750767a': 107, '0x4865e85c72a27ca6c362da75ba6707c07464b953': 88, '0x294308484f47ff5a833a284ac6949eb02728fbe4': 82, '0xe19e5f100d6a31169b5dca265c9285059c41d4f6': 61, '0xa39fcb48adf288f143459d57a1a0756718c919ae': 54, '0xdc84953d7c6448e498eb3c33ab0f815da5d13999': 52, '0x0f26c26318872e8fa85dee5d30cba45ed53b3d3e': 47, '0x7894ccf2997c8c89a80b86faa012d09d53ed48b9': 41, '0x007d42b9192b8c087b0d3e6ef73aae48e74b41c1': 36, '0x4028b9672bfd71ba2fcd97a6c82e06f72eaa14ba': 35, '0xf835b307bc5348194ae01ed729170c84217ba688': 34, '0xf7070fc72e2b92c6309785a39338d7c919a3cf4a': 31, '0xba69e7c96e9541863f009e713caf26d4ad2241a0': 31, '0xcff9cb72d19c10df754ae7be6d280e379cdb2354': 30, '0xa502f8112b2491718855f01a01a60462cc97a0d5': 29, '0x3325439082ff8ba7371dfdaa1af297bbfcac21b2': 26, '0xa83c4a6d0418074655bdbe74fed8435c46c19f66': 26, '0x80d9c4f6209044de069c545f68644419b520a02f': 24, '0xf243688304fa4f6c6efadc22b9c1dd009aa76650': 24, '0x4229a873bbd207deef8f41e807e563c26033d118': 20, '0xfe3672eff595cfd36ed05aaf4622d1aec3b5e852': 19, '0x16a4ff536001405f2b0d7ddafc79f6a10d024640': 19, '0xbe46324018124b2d604c2f3eae91d3de9b388b09': 18, '0x9d5bdaa9d82782c03402dd5c675ae3e45b3102e2': 18, '0x4668cd871eba35997e1fbe66d0eddf6612d018ce': 17, '0xa864694cacdf27900afb3c32b1b07aea3c465dde': 17, '0x422f8015c5d8168edee923749701360a8a4d0703': 17, '0xe861ad00aed0f04b41c675ec1c1493d2ebcbe776': 16, '0x258d778e4771893758dfd3e7dd1678229320eeb5': 16, '0xee462a6717f17c57c826f1ad9b4d3813495296c9': 16, '0x24ec083b6a022099003e3d035fed48b9a58296e5': 15, '0x316201f586706aaa2795bc2a3f0bad2379c363e4': 15, '0x1afd952269873fe009c7bdff5f07fd91605a7227': 15, '0xf767fca8e65d03fe16d4e38810f5e5376c3372a8': 15, '0xa379bbdd0af814502eb9b38d475c7fa7411bb4ec': 13, '0x428da5ff72d8be0efaa85336b6c6a9fc9e0f73fe': 13, '0x1368e088682b3ea455c4856297365542ca6828d8': 13, '0x750241c16c9fb878a7afd2b07b80f53e02c3f634': 13, '0xbb9854bfd082c48b4d426ac6a2a152b01326f46f': 11, '0x8f13a1d43408b6434dd10e161361386f3952d665': 11, '0x37b53b46fa74ac3f9b4340dc5a39aabb0f2afa33': 8, '0x49c3019b7a83b3c77a823255533975969027308d': 8, '0x09515cb5e3acaef239ab83d78b2f3e3764fcab9b': 7, '0xd12d8f8dfa54f1578b2177f99b2e282367b66b13': 7, '0x41f2d5040726c5328f8366f17041ec012ac8f338': 7, '0x2a53f42ad8bba138c21b50a4e5711f18381a61e9': 7, '0x062524205ca7ecf27f4a851edec93c7ad72f427b': 7, '0x55d035ba1f4ae932cf98125b93d830d9858cd39f': 6, '0x43e49c79172a1be3ebb4240da727c0da0fa5d233': 6, '0xcaaca224e35d0a1fa3304a3c4ec8beb5f28a99aa': 6, '0x49f053b866c33185fa1151e71fc80d5fe6b08a92': 5, '0x5a437d94843541d5cb83221a4a4b253de30b97b7': 5, '0xb1d58bad78f33892719cdeba218f8641a71a3f05': 5, '0x0389a06b028526b05966c287370bebefa0082176': 5, '0x51170b18bca7896b49c52dcc18e66e5c921e100f': 5, '0xc357a046c5c13bb4e6d918a208b8b4a0ab2f2efd': 5, '0xbe181da06d93867af0a3ffadcebe345ec35dae4e': 4, '0xa259e6bcade86c770cb5214c789ee107662831a6': 4, '0x99d982e49bcb5465a6b4c1e0ec4341c912d9ba42': 4, '0xf70ce1be9685b0cfb531bc712d3faace858b5bfb': 4, '0x02b2101903eb6a51518e63e84b785180859fda9d': 4, '0xa0f9fb2170dc2d181ef8aaf3571dc441813e0154': 4, '0xe7f06e64e0d04c6cfedf7e9079d56d0fb7200a2e': 4, '0x19a6067538c90973ef5dc31ded5fa567f3d09059': 3, '0x89c2352cb600df56fe4bfb5882caadef3e96213f': 3, '0x1ff3f56609d0771abb49566600febade0e708beb': 3, '0x8ea6c8077d6316b46e449aec8fb60a606cf50eea': 3, '0x1bb6123913d0b48948de38c3b75fd3eb3b4fe7e3': 3, '0x7d3ae940eb73dc9131758ad2e326c7d863b0916a': 3, '0x772cba2f87f92e95bb8ffa96187bbedebbb484d3': 2, '0x7fcc7ed28c99f64f721be410ad816247925aade8': 2, '0x4398a4a10347d8f18029c07853a7a689eebbb925': 2, '0xf1aa63ad7a897ca02cab6021513ee0a86820153e': 2, '0x9f1d916a456b96146e9f0dbbd0e107a1f389a061': 2, '0xa850e6f693b9bcb31df3ee44e7888ef19e608107': 1, '0x9da7902394fb19ddd340d47398d35e3405bf79ec': 1, '0xe1388626c8de5fd7e5683a83d8da6a34153e9b18': 1, '0x3ab274f835d1939d20d0bbb72a1fb513d7a7a675': 1, '0x0444f06a52320af2df7e60d1923080002838ce93': 1, '0xebfed9e4ae035b0f7ae982d1a7abfe0aa26a0341': 1, '0x275498d1fb7ffb5b521f89b23c84224af9f96ea6': 1, '0xba3048b17d1e8c1412ea29af9af795786065b5f9': 1, '0x1492cdd605d91658f228eab14d8444b60e6da8df': 1, '0x60acd43314d93f38507f3fd12e84225a5a099229': 1, '0xe4c1c33ed635263c61bf61db751b8a74ee3af0e4': 1, '0x870fe80e76dae4a4c12690dec52456ab13176202': 1, '0x83651a62b632c261442f396ad7202fe2a4995e3a': 1, '0xf93ca51746ce6e1cc2485c534eebe71ae987a7ad': 1, '0xa26b0a2fc7702ac3cdd4d578df7ef87ecf17908e': 1}